### ISSUE TITLE
package.json has wrong URL

### ISSUE THREAD

**Issue by peterflynn** [jbardnz/RightClickExtended#7]
The version on the Extension Registry provides the wrong `"homepage"` URL -- https://github.com/jbardnz/Brackets-RightClickExtended -- so clicking the "More Info" link in Brackets's Extension Manager goes to the wrong location.

It looks like package.json is already correct in the repo here, so a new version just needs to get uploaded to the registry...

**Comment by jbardnz** [comment]
Hi

Thanks for logging this and I appologise for the slow reply. I have updated the registry with the latest version.
